min_score: 4.0

keywords:
  # --- SISTEMAS OPERATIVOS ---
  - "Windows 10"
  - "Windows 11"
  - "Windows Server"
  - "Debian"
  - "Ubuntu"
  - "Linux Mint"
  - "Kali Linux"
  - "Android"

  # --- VIRTUALIZACIÓN Y NUBE ---
  - "VMware"
  - "VirtualBox"
  - "Hyper-V"
  - "Docker"
  - "Kubernetes"
  - "Azure"

  # --- REDES Y FIREWALLS ---
  - "Fortinet"
  - "Fortigate"
  - "Cisco"
  - "Palo Alto Networks"
  - "Sonicwall"
  - "Citrix"
  - "Netscaler"
  - "Ubiquiti"
  - "Unifi"

  # --- ALMACENAMIENTO (NAS) ---
  - "Synology"
  - "QNAP"

  # --- HERRAMIENTAS DE PENTESTING Y SEGURIDAD ---
  - "Wireshark"
  - "Metasploit"
  - "Burp Suite"
  - "OpenSSL"
  - "Crowdstrike"
  - "Bitdefender"
  - "Sophos"

  # --- NAVEGADORES ---
  - "Chrome"
  - "Firefox"
  - "Edge"

  # --- procesadores y graficas ---
  - "AMD"
  - "Intel"
  - "Radeon"
  - "Nvidea"

early_warning_sources:
  # --- ALERTAS TÉCNICAS (Sección Naranja) ---
  # Microsoft Security Update Guide
  - "https://api.msrc.microsoft.com/update-guide/rss"
  # Debian Security
  - "https://www.debian.org/security/dsa-long"
  # Incibe Avisos (Técnicos - General)
  - "https://www.incibe.es/incibe-cert/alerta-temprana/avisos/feed"
  # Incibe Avisos SCI (Sistemas de Control Industrial)
  - "https://www.incibe.es/incibe-cert/alerta-temprana/avisos-sci/feed"

news_sources:
  # --- LECTURA Y ACTUALIDAD (Sección Azul) ---
  # Incibe Bitácora (Noticias en Español)
  - "https://www.incibe.es/incibe-cert/publicaciones/bitacora-ciberseguridad/feed"
  # The Hacker News
  - "https://feeds.feedburner.com/TheHackersNews"
  # Bleeping Computer
  - "https://www.bleepingcomputer.com/feed/"
  # WeLiveSecurity (ESET)
  - "https://www.welivesecurity.com/feed/"
